version: 1

stack:
  name: bluegreen-demo

services:
  db:
    runtime: docker
    image: postgres:16
    env:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    health:
      tcp:
        address: 127.0.0.1:5432
        interval: 3s
        timeout: 1s
        failures: 5

  api:
    runtime: docker
    image: ghcr.io/example/api:1.2.3
    command: ["./server"]
    replicas: 2
    env:
      DATABASE_URL: postgres://postgres:postgres@db:5432/app?sslmode=disable
    dependsOn:
      - target: db
        require: ready
    ports: ["8080:8080"]
    health:
      http:
        url: http://127.0.0.1:8080/healthz
        expectStatus: [200]
        interval: 5s
        timeout: 2s
        failureThreshold: 3
    update:
      strategy: blueGreen
      abortAfterFailures: 2
      observationWindow: 3m
      blueGreen:
        switch: proxyLabel
        drainTimeout: 30s
        rollbackWindow: 1m
